version: '3.5'

services:

  server-one:
    container_name: server-one
    image: lombocska/server-one
    ports:
      - "8080:8080"
    environment:
      SERVER_TWO_RESOURCE_URL: server-two:8081
    networks:
      - sleuth-example
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  server-two:
    container_name: server-two
    image: lombocska/server-two
    networks:
      - sleuth-example
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

networks:
  sleuth-example:
    driver: bridge
