spring:
  application:
    name: '@name@'
  sleuth:
    propagation-keys:
      - "lombocska-request-id"  #baggage field that gets propagated with traceId from HTTP Request Header
    log.slf4j.whitelisted-mdc-keys:
      - "lombocska-request-id" #makes possible to use this custom propagation keys in logs
    propagation:
      tag:
        whitelisted-keys:
          - "lombocska-request-id"
    keys:
      http:
        headers:
          - "lombocska-request-id"
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}

edge-service:
  resource-url:
    platform-service-producer: ${PLATFORM_SERVICE_PRODUCER_RESOURCE_URL:localhost:8081}

