server:
  port: 8081

spring:
  application:
    name: '@name@'
  sleuth:
    propagation-keys:
      - "lombocska-request-id"
    log.slf4j.whitelisted-mdc-keys:
      - "lombocska-request-id"
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

lombocska:
  kafka:
    topic: ${KAFKA_TOPIC:zipkin-sleuth-example-topic}
